# Generated by Django 3.0.3 on 2020-08-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expired_date',
            new_name='date_expired',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='registered_date',
            new_name='date_joined',
        ),
    ]
