# Generated by Django 3.0.3 on 2020-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0002_auto_20200912_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to='attachments/'),
        ),
    ]
