# Generated by Django 3.0.3 on 2020-08-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0002_auto_20200813_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phs_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
