# Generated by Django 3.0.3 on 2020-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0003_auto_20200912_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troublegroup',
            name='is_common_trouble',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='よくあるトラブルフラグ'),
        ),
    ]
