# Generated by Django 3.0.3 on 2020-08-13 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0003_auto_20200813_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator('Invalid email address.')]),
        ),
    ]
