# Generated by Django 3.0.3 on 2020-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0004_auto_20201125_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleevent',
            name='trigger',
            field=models.TextField(blank=True, null=True, verbose_name='発生時の操作'),
        ),
    ]
