# Generated by Django 3.0.3 on 2020-11-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0005_troubleevent_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationMetaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='メタ運転タイプ名称')),
            ],
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='trigger',
            field=models.TextField(blank=True, null=True, verbose_name='発生の契機となる操作'),
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='運転タイプ名称')),
                ('meta_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.OperationMetaType', verbose_name='メタ運転タイプ')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True, verbose_name='開始日時')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('num_treat_hc1', models.IntegerField(blank=True, null=True, verbose_name='HC1 治療ポート数')),
                ('num_treat_gc2', models.IntegerField(blank=True, null=True, verbose_name='GC2 治療ポート数')),
                ('num_qa_hc1', models.IntegerField(blank=True, null=True, verbose_name='HC1 QAポート数')),
                ('num_qa_gc2', models.IntegerField(blank=True, null=True, verbose_name='GC2 QAポート数')),
                ('operation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.OperationType', verbose_name='運転タイプ')),
            ],
        ),
    ]
