# Generated by Django 3.0.3 on 2020-08-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0005_auto_20200817_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=100, verbose_name='エラーコード')),
            ],
        ),
        migrations.DeleteModel(
            name='ErrorMessage',
        ),
    ]
