# Generated by Django 3.0.3 on 2020-08-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0007_error_error_descrption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='error_descrption',
            new_name='error_description',
        ),
    ]
