# Generated by Django 3.0.3 on 2020-08-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0008_auto_20200817_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleevent',
            name='errors',
            field=models.ManyToManyField(to='ptop.Error', verbose_name='エラーメッセージ'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='device_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.Device', verbose_name='デバイスID'),
        ),
    ]
