# Generated by Django 3.0.3 on 2020-12-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0009_troubleevent_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleevent',
            name='delaytime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='治療遅延時間'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='downtime',
            field=models.PositiveIntegerField(null=True, verbose_name='装置故障時間'),
        ),
    ]
