# Generated by Django 3.0.3 on 2020-08-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0010_auto_20200817_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.Device', verbose_name='デバイスID'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='errors',
            field=models.ManyToManyField(blank=True, null=True, to='ptop.Error', verbose_name='エラーメッセージ'),
        ),
    ]
