# Generated by Django 3.0.3 on 2020-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0011_auto_20201209_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='原因タイプ名称')),
            ],
        ),
        migrations.CreateModel(
            name='HandlingStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='対応状況名称')),
            ],
        ),
        migrations.CreateModel(
            name='VendorStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='メーカー報告状況名称')),
            ],
        ),
    ]
