# Generated by Django 3.0.3 on 2020-08-17 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0012_auto_20200817_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troubleevent',
            name='errors',
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='approval_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleevent_approved', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='device id'),
        ),
    ]
