# Generated by Django 3.0.3 on 2020-12-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0012_causetype_handlingstatustype_vendorstatustype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troublegroup',
            name='causetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.CauseType', verbose_name='原因の類型'),
        ),
        migrations.AlterField(
            model_name='troublegroup',
            name='handling_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.HandlingStatusType', verbose_name='対処状況'),
        ),
        migrations.AlterField(
            model_name='troublegroup',
            name='vendor_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.VendorStatusType', verbose_name='メーカー連絡状況'),
        ),
    ]
