# Generated by Django 3.0.3 on 2020-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0013_auto_20201211_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='デバイスID'),
        ),
        migrations.AlterField(
            model_name='error',
            name='error_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='エラーコード'),
        ),
    ]
