# Generated by Django 3.0.3 on 2020-08-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0013_auto_20200817_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troubleevent',
            old_name='device_id',
            new_name='device',
        ),
    ]
