# Generated by Django 3.0.3 on 2020-08-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0015_auto_20200817_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleevent',
            name='error_message',
            field=models.CharField(blank=True, max_length=100, verbose_name='エラーメッセージ'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='トラブル名称'),
        ),
        migrations.CreateModel(
            name='TroubleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='トラブル分類名称')),
                ('description', models.TextField(null=True, verbose_name='内容')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='原因')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.Device', verbose_name='デバイスID')),
            ],
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.TroubleGroup', verbose_name='トラブル分類'),
        ),
    ]
