# Generated by Django 3.0.3 on 2020-12-21 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0016_auto_20201221_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleevent',
            name='handling_operators',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('groups__name', 'Operator'), ('is_active', True)), to=settings.AUTH_USER_MODEL, verbose_name='対応者'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='input_operator',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Operator'), ('is_active', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleevent_inputed', to=settings.AUTH_USER_MODEL, verbose_name='入力者'),
        ),
    ]
