# Generated by Django 3.0.3 on 2021-01-07 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0017_auto_20201221_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='題名')),
                ('description', models.TextField(null=True, verbose_name='内容')),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成時刻')),
                ('user', models.ForeignKey(limit_choices_to=models.Q(is_active=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_inputed', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
    ]
