# Generated by Django 3.0.3 on 2020-08-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0017_auto_20200818_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troubleevent',
            old_name='device_id',
            new_name='deviceid',
        ),
    ]
