# Generated by Django 3.0.3 on 2020-08-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0018_auto_20200818_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troubleevent',
            name='deviceid',
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.Device', verbose_name='デバイス'),
        ),
    ]
