# Generated by Django 3.0.3 on 2020-08-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0019_auto_20200818_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='troubleevent',
            name='error_message',
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='errors',
            field=models.ManyToManyField(to='ptop.Error', verbose_name='エラーメッセージ'),
        ),
    ]
