# Generated by Django 3.0.3 on 2020-08-18 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0020_auto_20200818_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleevent',
            name='reported_physicist',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_physicist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleevent_reported', to=settings.AUTH_USER_MODEL, verbose_name='報告した物理士'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_physicist',
            field=models.BooleanField(default=False, help_text='医学物理士である場合にチェックする。「報告した物理士」一覧に表示される。.'),
        ),
    ]
