# Generated by Django 3.0.3 on 2021-01-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0020_operation_operation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ptop.TroubleGroup', verbose_name='投稿先のトラブル類型'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成時刻'),
        ),
    ]
