# Generated by Django 3.0.3 on 2021-03-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0021_auto_20210119_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='影響範囲名称')),
                ('hc1_flag', models.BooleanField(verbose_name='HC1に影響があればTrue')),
                ('gc2_flag', models.BooleanField(verbose_name='GC2に影響があればTrue')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='治療可否タイプ名称')),
                ('treatment_available_flag', models.BooleanField(verbose_name='治療可ならTrue')),
            ],
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='緊急性名称')),
            ],
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='effect_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.EffectScope', verbose_name='影響範囲'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='treatment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.TreatmentStatusType', verbose_name='発生中の治療可否状況'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='urgency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.Urgency', verbose_name='対処緊急性'),
        ),
    ]
