# Generated by Django 3.0.3 on 2020-08-18 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0021_auto_20200818_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleevent',
            name='reported_physicist',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'Physicist'), ('is_active', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleevent_reported', to=settings.AUTH_USER_MODEL, verbose_name='報告した物理士'),
        ),
    ]
