# Generated by Django 3.0.3 on 2021-03-04 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0023_auto_20210304_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='handling_operators',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(('groups__name', 'Operator'), ('groups__name', 'Physicist'), _connector='OR'), ('is_active', True)), to=settings.AUTH_USER_MODEL, verbose_name='対応者'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='input_operator',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('groups__name', 'Operator'), ('groups__name', 'Physicist'), _connector='OR'), ('is_active', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleevent_inputed', to=settings.AUTH_USER_MODEL, verbose_name='入力者'),
        ),
    ]
