# Generated by Django 3.0.3 on 2020-08-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0023_auto_20200818_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_operator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_physicist',
        ),
    ]
