# Generated by Django 3.0.3 on 2020-08-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0025_auto_20200824_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='troublegroup',
            name='criticality_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='FMEA致命度スコア'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='difficulty_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='FMEA対応難度スコア'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='frequency_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='FMEA発生頻度スコア'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='is_common_trouble',
            field=models.BooleanField(default=False, verbose_name='よくあるトラブルフラグ'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='permanent_action',
            field=models.TextField(blank=True, null=True, verbose_name='恒久対策の内容'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='reminder_datetime',
            field=models.DateField(blank=True, null=True, verbose_name='振り返り予定日'),
        ),
    ]
