# Generated by Django 3.0.3 on 2021-04-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0027_auto_20210323_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltroubleevent',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='復旧完了時刻'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='復旧完了時刻'),
        ),
        migrations.AlterField(
            model_name='historicaltroubleevent',
            name='downtime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='運転停止時間'),
        ),
        migrations.AlterField(
            model_name='historicaltroubleevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='運転再開時刻'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='downtime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='運転停止時間'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='運転再開時刻'),
        ),
    ]
