# Generated by Django 3.0.3 on 2021-05-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0028_auto_20210415_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_time',
            new_name='posted_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時刻'),
        ),
    ]
