# Generated by Django 3.0.3 on 2021-06-09 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0029_auto_20210512_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ptop.TroubleGroup', verbose_name='投稿先のトラブル類型'),
        ),
    ]
