# Generated by Django 3.2.6 on 2021-10-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0030_auto_20210609_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='項目名称')),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicaltroubleevent',
            name='require_detail',
            field=models.TextField(blank=True, null=True, verbose_name='要望詳細'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='require_detail',
            field=models.TextField(blank=True, null=True, verbose_name='要望詳細'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='require_items',
            field=models.ManyToManyField(blank=True, to='ptop.RequireType', verbose_name='要望項目'),
        ),
    ]
