# Generated by Django 3.2.6 on 2021-10-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0031_auto_20211012_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleevent',
            name='require_items',
            field=models.ManyToManyField(blank=True, null=True, to='ptop.RequireType', verbose_name='要望項目'),
        ),
    ]
