# Generated by Django 3.2.6 on 2021-10-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0032_alter_troubleevent_require_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltroubleevent',
            name='require_detail',
        ),
        migrations.RemoveField(
            model_name='troubleevent',
            name='require_detail',
        ),
        migrations.RemoveField(
            model_name='troubleevent',
            name='require_items',
        ),
        migrations.AddField(
            model_name='historicaltroublegroup',
            name='require_detail',
            field=models.TextField(blank=True, null=True, verbose_name='要望詳細'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='require_detail',
            field=models.TextField(blank=True, null=True, verbose_name='要望詳細'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='require_items',
            field=models.ManyToManyField(blank=True, null=True, to='ptop.RequireType', verbose_name='要望項目'),
        ),
    ]
