# Generated by Django 3.2.6 on 2021-10-14 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0034_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltroublegroup',
            name='effect_scope',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ptop.effectscope', verbose_name='影響範囲'),
        ),
        migrations.AddField(
            model_name='historicaltroublegroup',
            name='treatment_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ptop.treatmentstatustype', verbose_name='発生中の治療可否状況'),
        ),
        migrations.AddField(
            model_name='historicaltroublegroup',
            name='urgency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ptop.urgency', verbose_name='対処緊急性'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='effect_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.effectscope', verbose_name='影響範囲'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='treatment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.treatmentstatustype', verbose_name='発生中の治療可否状況'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='urgency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.urgency', verbose_name='対処緊急性'),
        ),
    ]
