# Generated by Django 3.2.6 on 2021-10-21 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0037_user_is_tcs_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('Invalid email address.')])),
                ('is_tcs_destination', models.BooleanField(default=True, help_text='不具合連絡票送信先に含める')),
                ('display_order', models.IntegerField()),
            ],
        ),
    ]
