# Generated by Django 3.2.6 on 2021-10-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0038_emailaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='残量単位')),
                ('initial_level', models.FloatField(verbose_name='デフォルト初期残量')),
                ('warning_level', models.FloatField(verbose_name='警告レベル')),
                ('exchange_level', models.FloatField(verbose_name='交換目標レベル')),
                ('fault_level', models.FloatField(verbose_name='機能停止レベル')),
                ('num_recomment', models.PositiveIntegerField(verbose_name='推奨在庫数')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('candidate_devices', models.ManyToManyField(to='ptop.Device', verbose_name='使用するデバイス')),
            ],
        ),
    ]
