# Generated by Django 3.2.8 on 2021-10-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0039_supplytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='シリアル番号')),
                ('remain_level', models.FloatField(verbose_name='寿命指標')),
                ('order_date', models.DateTimeField(null=True, verbose_name='発注日')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='納品予定日')),
                ('stock_date', models.DateTimeField(blank=True, null=True, verbose_name='納品日')),
                ('install_date', models.DateTimeField(blank=True, null=True, verbose_name='使用開始日')),
                ('uninstall_date', models.DateTimeField(blank=True, null=True, verbose_name='使用終了日')),
                ('dispose_date', models.DateTimeField(blank=True, null=True, verbose_name='使用終了日')),
                ('is_installed', models.BooleanField(default=False, verbose_name='使用中フラグ')),
                ('is_available', models.BooleanField(default=False, verbose_name='使用可能フラグ')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('installed_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ptop.device', verbose_name='設置デバイス')),
            ],
        ),
        migrations.AddField(
            model_name='supplytype',
            name='name',
            field=models.CharField(default='消耗品', max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='troublegroup',
            name='require_items',
            field=models.ManyToManyField(blank=True, to='ptop.RequireType', verbose_name='要望項目'),
        ),
        migrations.CreateModel(
            name='SupplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(verbose_name='寿命指標測定結果')),
                ('date', models.DateTimeField(verbose_name='測定日時')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptop.device', verbose_name='設置デバイス')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptop.supplyitem', verbose_name='消耗品個体')),
            ],
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptop.supplytype', verbose_name='消耗品形式'),
        ),
    ]
