# Generated by Django 3.2.6 on 2021-10-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0041_auto_20211029_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplyitem',
            old_name='type',
            new_name='supplytype',
        ),
    ]
