# Generated by Django 3.2.6 on 2021-11-02 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0045_room_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ptop.storage', verbose_name='保管場所'),
        ),
        migrations.AddField(
            model_name='supplytype',
            name='candidate_storage',
            field=models.ManyToManyField(to='ptop.Storage', verbose_name='保管場所'),
        ),
    ]
