# Generated by Django 3.2.6 on 2021-11-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0046_auto_20211102_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='place_list',
        ),
        migrations.AddField(
            model_name='storage',
            name='num_subplace',
            field=models.IntegerField(default=0, verbose_name='段数'),
        ),
    ]
