# Generated by Django 3.2.6 on 2021-11-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0047_auto_20211102_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplytype',
            name='estimation_method',
            field=models.CharField(default='linear', max_length=10, verbose_name='寿命予測方法'),
        ),
    ]
