# Generated by Django 3.2.6 on 2021-12-04 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0049_auto_20211102_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='dispose_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='廃棄日'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='期限日')),
                ('description', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('is_done', models.BooleanField(default=False, verbose_name='処理済みフラグ')),
                ('after_description', models.TextField(blank=True, null=True, verbose_name='処置メモ')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptop.troublegroup', verbose_name='対象トラブル類型')),
                ('reminder_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptop.remindertype', verbose_name='種類')),
            ],
        ),
    ]
