# Generated by Django 3.2.6 on 2021-12-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0050_auto_20211204_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindertype',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
