# Generated by Django 3.2.8 on 2022-04-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0052_reminder_done_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeamDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IrradiationTechnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, verbose_name='治療室ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OpeartionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_course', models.CharField(max_length=100, verbose_name='コース')),
                ('num_complete', models.IntegerField(default=0, verbose_name='完遂数')),
                ('num_canceled_by_patient', models.IntegerField(default=0, verbose_name='患者都合中止数')),
                ('num_canceled_by_machine', models.IntegerField(default=0, verbose_name='装置都合中止数')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptop.operation', verbose_name='運転内容')),
            ],
        ),
        migrations.CreateModel(
            name='BeamCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100, verbose_name='コースID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('is_clinical', models.BooleanField(default=True, verbose_name='治療可')),
                ('display_order', models.IntegerField(default=0)),
                ('irradiation_technique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.irradiationtechnique', verbose_name='照射方式')),
                ('treatment_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptop.treatmentroom', verbose_name='治療室')),
            ],
        ),
    ]
