# Generated by Django 3.2.8 on 2022-04-05 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0053_beamcourse_beamdirection_irradiationtechnique_opeartionresult_treatmentroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamcourse',
            name='beam_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.beamdirection', verbose_name='ビーム方向'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='errors',
            field=models.ManyToManyField(blank=True, to='ptop.Error', verbose_name='エラーメッセージ'),
        ),
        migrations.AlterField(
            model_name='troublegroup',
            name='errors',
            field=models.ManyToManyField(blank=True, to='ptop.Error', verbose_name='エラーメッセージ'),
        ),
    ]
