# Generated by Django 3.2.8 on 2022-04-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0054_auto_20220405_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeartionResult',
            new_name='OperationResult',
        ),
    ]
