# Generated by Django 3.2.8 on 2022-04-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0055_rename_opeartionresult_operationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationresult',
            name='beam_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptop.beamcourse', verbose_name='コース'),
        ),
    ]
