# Generated by Django 3.2.8 on 2022-04-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0056_alter_operationresult_beam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationresult',
            name='operation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ptop.operationtype', verbose_name='運転タイプ'),
        ),
        migrations.AlterField(
            model_name='operationresult',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptop.operation', verbose_name='運転記録'),
        ),
    ]
