# Generated by Django 3.2.8 on 2022-05-10 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0057_auto_20220423_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltroubleevent',
            name='causetype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ptop.causetype', verbose_name='原因の類型'),
        ),
        migrations.AddField(
            model_name='historicaltroubleevent',
            name='energy_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='EID'),
        ),
        migrations.AddField(
            model_name='historicaltroubleevent',
            name='intensity_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IID'),
        ),
        migrations.AddField(
            model_name='historicaltroubleevent',
            name='irradiation_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='照射番号'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='causetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptop.causetype', verbose_name='原因の類型'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='energy_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='EID'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='intensity_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IID'),
        ),
        migrations.AddField(
            model_name='troubleevent',
            name='irradiation_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='照射番号'),
        ),
    ]
