# Generated by Django 3.2.8 on 2022-05-17 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('ptop', '0058_auto_20220510_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Particle Therapy Database of Operation and Maintenance', max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(default='粒子線治療装置の運転・維持管理用のデータベース', max_length=255, verbose_name='サイトの説明')),
                ('keywords', models.CharField(default='Database, Trouble, Operation', max_length=255, verbose_name='サイトのキーワード')),
                ('facility', models.CharField(default='', max_length=255, verbose_name='施設名')),
                ('machine', models.CharField(default='重粒子線治療装置', max_length=255, verbose_name='装置名')),
                ('database', models.CharField(default='運転・維持管理データベース', max_length=255, verbose_name='データベース名')),
                ('administrator', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site', verbose_name='Site')),
            ],
        ),
    ]
