# Generated by Django 3.2.8 on 2022-05-17 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0059_sitedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='administrator',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
    ]
