# Generated by Django 3.2.8 on 2022-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0060_alter_sitedetail_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetail',
            name='eid_name',
            field=models.CharField(default='EID', max_length=255, verbose_name='EID名称'),
        ),
        migrations.AddField(
            model_name='sitedetail',
            name='iid_name',
            field=models.CharField(default='EID', max_length=255, verbose_name='IID名称'),
        ),
        migrations.AddField(
            model_name='sitedetail',
            name='irr_num_name',
            field=models.CharField(default='照射番号', max_length=255, verbose_name='照射番号名称'),
        ),
    ]
