# Generated by Django 4.0.4 on 2022-05-24 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0061_auto_20220517_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltroubleevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical trouble event', 'verbose_name_plural': 'historical trouble events'},
        ),
        migrations.AlterModelOptions(
            name='historicaltroublegroup',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical trouble group', 'verbose_name_plural': 'historical trouble groups'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inputed', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inputed', to=settings.AUTH_USER_MODEL, verbose_name='入力者'),
        ),
        migrations.AlterField(
            model_name='historicaltroubleevent',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltroublegroup',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='approval_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='input_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inputed', to=settings.AUTH_USER_MODEL, verbose_name='入力者'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='reported_physicist',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'Physicist'), ('is_active', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reported', to=settings.AUTH_USER_MODEL, verbose_name='報告した物理士'),
        ),
        migrations.AlterField(
            model_name='troublegroup',
            name='classify_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_classified', to=settings.AUTH_USER_MODEL, verbose_name='分類作成者'),
        ),
    ]
