# Generated by Django 4.0.4 on 2023-01-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0062_alter_historicaltroubleevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltroubleevent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical trouble event'},
        ),
        migrations.AlterModelOptions(
            name='historicaltroublegroup',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical trouble group'},
        ),
        migrations.AlterField(
            model_name='historicaltroubleevent',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaltroublegroup',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
